type Grid = (string | null)[][];
const _ = null;

// Base colors (used by starters + base grids)
const E='#2d1b00',R='#ff6b6b',W='#fff8e7';
const S='#f4c87a',F='#f5a623',T='#e8935a';
const B='#a8d8ea',G='#98d8c8';
const GR='#888888',DK='#333333';

// Grid builder: '.' = null, other chars = colors from palette
function g(rows: string[], p: Record<string,string>): Grid {
  return rows.map(r => r.split('').map(c => c==='.' ? null : (p[c] ?? null)));
}

// ── Base grids ────────────────────────────────────────────────────────────────

const EGG: Grid = [
  [_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_],
  [_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_],
  [_,_,_,_,_,W,W,W,W,W,W,_,_,_,_,_],
  [_,_,_,W,W,W,W,W,W,W,W,W,W,_,_,_],
  [_,_,W,W,W,W,W,W,W,W,W,W,W,W,_,_],
  [_,_,W,W,W,W,W,W,W,W,W,W,W,W,_,_],
  [_,_,W,W,W,W,W,W,W,W,W,W,W,W,_,_],
  [_,_,W,W,W,W,W,W,W,W,W,W,W,W,_,_],
  [_,_,W,W,W,W,W,W,W,W,W,W,W,W,_,_],
  [_,_,W,W,W,W,W,W,W,W,W,W,W,W,_,_],
  [_,_,W,W,W,W,W,W,W,W,W,W,W,W,_,_],
  [_,_,_,W,W,W,W,W,W,W,W,W,W,_,_,_],
  [_,_,_,_,_,W,W,W,W,W,W,_,_,_,_,_],
  [_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_],
  [_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_],
  [_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_],
];
const SLIM: Grid = [
  [_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_],
  [_,_,_,_,_,S,S,S,S,S,S,_,_,_,_,_],
  [_,_,_,_,S,S,S,S,S,S,S,S,_,_,_,_],
  [_,_,_,_,S,S,E,S,S,E,S,S,_,_,_,_],
  [_,_,_,_,S,S,S,R,S,S,S,S,_,_,_,_],
  [_,_,_,_,S,S,S,S,S,S,S,S,_,_,_,_],
  [_,_,_,_,_,S,S,S,S,S,S,_,_,_,_,_],
  [_,_,_,B,B,S,S,S,S,S,S,B,B,_,_,_],
  [_,_,_,B,B,S,S,S,S,S,S,B,B,_,_,_],
  [_,_,_,_,B,S,S,S,S,S,S,B,_,_,_,_],
  [_,_,_,_,_,S,S,_,_,S,S,_,_,_,_,_],
  [_,_,_,_,_,S,S,_,_,S,S,_,_,_,_,_],
  [_,_,_,_,G,G,G,_,_,G,G,G,_,_,_,_],
  [_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_],
  [_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_],
  [_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_],
];
const CHUBBY: Grid = [
  [_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_],
  [_,_,_,_,F,F,F,F,F,F,F,F,_,_,_,_],
  [_,_,_,F,F,F,F,F,F,F,F,F,F,_,_,_],
  [_,_,_,F,F,E,F,F,F,E,F,F,F,_,_,_],
  [_,_,_,F,F,F,F,R,F,F,F,F,F,_,_,_],
  [_,_,_,F,F,F,F,F,F,F,F,F,F,_,_,_],
  [_,_,_,_,F,F,F,F,F,F,F,F,_,_,_,_],
  [_,_,_,B,F,F,F,F,F,F,F,F,B,_,_,_],
  [_,_,B,B,F,F,F,F,F,F,F,F,B,B,_,_],
  [_,_,_,B,F,F,F,F,F,F,F,F,B,_,_,_],
  [_,_,_,_,F,F,F,_,_,F,F,F,_,_,_,_],
  [_,_,_,_,F,F,F,_,_,F,F,F,_,_,_,_],
  [_,_,_,G,G,G,G,_,_,G,G,G,G,_,_,_],
  [_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_],
  [_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_],
  [_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_],
];
const FAT: Grid = [
  [_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_],
  [_,_,_,T,T,T,T,T,T,T,T,T,T,_,_,_],
  [_,_,T,T,T,T,T,T,T,T,T,T,T,T,_,_],
  [_,_,T,T,E,T,T,T,T,T,E,T,T,T,_,_],
  [_,_,T,T,T,T,T,R,T,T,T,T,T,T,_,_],
  [_,_,T,T,T,T,T,T,T,T,T,T,T,T,_,_],
  [_,_,T,T,T,T,T,T,T,T,T,T,T,T,_,_],
  [_,_,T,T,T,T,T,T,T,T,T,T,T,T,_,_],
  [_,T,T,T,T,T,T,T,T,T,T,T,T,T,T,_],
  [_,_,T,T,T,T,T,T,T,T,T,T,T,T,_,_],
  [_,_,_,_,T,T,T,_,_,T,T,T,_,_,_,_],
  [_,_,_,_,T,T,T,_,_,T,T,T,_,_,_,_],
  [_,_,_,G,G,G,G,G,G,G,G,G,G,_,_,_],
  [_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_],
  [_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_],
  [_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_],
];
const ZOMBIE: Grid = [
  [_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_],
  [_,_,_,_,GR,GR,GR,GR,GR,GR,GR,GR,_,_,_,_],
  [_,_,_,GR,GR,GR,GR,GR,GR,GR,GR,GR,GR,_,_,_],
  [_,_,_,GR,GR,DK,GR,GR,GR,DK,GR,GR,GR,_,_,_],
  [_,_,_,GR,GR,GR,GR,R,GR,GR,GR,GR,GR,_,_,_],
  [_,_,_,GR,GR,GR,GR,GR,GR,GR,GR,GR,GR,_,_,_],
  [_,_,_,_,GR,GR,GR,GR,GR,GR,GR,GR,_,_,_,_],
  [_,_,GR,_,GR,GR,GR,GR,GR,GR,GR,GR,_,GR,_,_],
  [_,GR,GR,_,GR,GR,GR,GR,GR,GR,GR,GR,_,GR,GR,_],
  [_,_,GR,_,GR,GR,GR,GR,GR,GR,GR,GR,_,GR,_,_],
  [_,_,_,_,GR,GR,GR,_,_,GR,GR,GR,_,_,_,_],
  [_,_,_,_,GR,GR,GR,_,_,GR,GR,GR,_,_,_,_],
  [_,_,_,DK,DK,DK,DK,_,_,DK,DK,DK,DK,_,_,_],
  [_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_],
  [_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_],
  [_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_],
];
const DEAD: Grid = [
  [_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_],
  [_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_],
  [_,_,_,_,_,DK,DK,DK,DK,DK,DK,_,_,_,_,_],
  [_,_,_,DK,DK,DK,DK,DK,DK,DK,DK,DK,DK,_,_,_],
  [_,_,DK,DK,DK,R,DK,DK,DK,R,DK,DK,DK,DK,_,_],
  [_,_,DK,DK,R,DK,R,DK,DK,R,DK,R,DK,DK,_,_],
  [_,_,DK,DK,DK,R,DK,DK,DK,R,DK,DK,DK,DK,_,_],
  [_,_,DK,DK,DK,DK,DK,DK,DK,DK,DK,DK,DK,DK,_,_],
  [_,_,DK,DK,DK,DK,DK,DK,DK,DK,DK,DK,DK,DK,_,_],
  [_,_,_,DK,DK,DK,DK,DK,DK,DK,DK,DK,DK,_,_,_],
  [_,_,_,_,_,DK,DK,_,_,DK,DK,_,_,_,_,_],
  [_,_,_,_,_,DK,DK,_,_,DK,DK,_,_,_,_,_],
  [_,_,_,_,DK,DK,DK,_,_,DK,DK,DK,_,_,_,_],
  [_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_],
  [_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_],
  [_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_],
];

const BASE_GRIDS: Grid[] = [EGG, SLIM, CHUBBY, FAT, ZOMBIE, DEAD];

// ── Character 01: ねむり (Sleepy) ─────────────────────────────────────────────
const C01S = g([
  '................',
  '.....aaaaaa.....',
  '....aaaaaaaa....',
  '....aaxxaaxxaa..',
  '....aaaaaaaaaaa.',
  '....aaaaaaaa....',
  '.....aaaaaa.....',
  '...ddaaaaaad....',
  '...ddaaaaaad....',
  '....daaaaaa.....',
  '.....aa..aa.....',
  '.....aa..aa.....',
  '....eee..eee....',
  '................',
  '................',
  '................',
],{a:'#e89060',d:'#f4b080',e:'#e09060',x:'#2d1b00'});
const C01C = g([
  '................',
  '....bbbbbbbb....',
  '...bbbbbbbbbb...',
  '...bbxxaaxxbb...',
  '...bbbbbbbbbbb..',
  '...bbbbbbbbbb...',
  '....bbbbbbbb....',
  '..dddbbbbbbddd..',
  '..dddbbbbbbddd..',
  '...ddbbbbbbd....',
  '.....bbb.bbb....',
  '.....bbb.bbb....',
  '...eeee..eeee...',
  '................',
  '................',
  '................',
],{b:'#d07040',d:'#f4b080',e:'#e09060',x:'#2d1b00'});
const C01F = g([
  '................',
  '...cccccccccc...',
  '..cccccccccccc..',
  '..ccxxaaxcc cc..',
  '..cccccccccccc..',
  '..cccccccccccc..',
  '..cccccccccccc..',
  '..cccccccccccc..',
  '.ccccccccccccc..',
  '..cccccccccccc..',
  '....ccc..ccc....',
  '....ccc..ccc....',
  '...eeeeeeeeee...',
  '................',
  '................',
  '................',
],{c:'#b85828',e:'#e09060',x:'#2d1b00',a:'#b85828'});

// ── Character 02: ひよこ (Chick) ──────────────────────────────────────────────
const C02S = g([
  '................',
  '......yyyy......',
  '....yyyyyyyy....',
  '....yyyyyyyyyyy.',
  '...yyxyyy xyyyy.',
  '...yyyyooyyyy...',
  '...yyyyyyyyy....',
  '....yyyyyyy.....',
  '....yyyyyyy.....',
  '.....yyyyy......',
  '.....oo.oo......',
  '.....oo.oo......',
  '................',
  '................',
  '................',
  '................',
],{y:'#f8d820',x:'#2d1b00',o:'#f5a020',' ':'#f8d820'});
const C02C = g([
  '................',
  '.....yyyyyy.....',
  '...yyyyyyyyyy...',
  '...yyyyyyyyyy...',
  '..yyxyyyy xyyyy.',
  '..yyyyyooyyyy...',
  '..yyyyyyyyyy....',
  '...yyyyyyyyy....',
  '...yyyyyyyyy....',
  '....yyyyyyy.....',
  '....oo..oo......',
  '....oo..oo......',
  '................',
  '................',
  '................',
  '................',
],{y:'#f0b800',x:'#2d1b00',o:'#f5a020',' ':'#f0b800'});
const C02F = g([
  '................',
  '....yyyyyyyy....',
  '..yyyyyyyyyyyy..',
  '..yyyyyyyyyyyy..',
  '..yyxyyyyyxyy...',
  '..yyyyyooyyyyy..',
  '..yyyyyyyyyyyy..',
  '..yyyyyyyyyyyy..',
  '.yyyyyyyyyyyyyy.',
  '..yyyyyyyyyyyy..',
  '....ooo.ooo.....',
  '....ooo.ooo.....',
  '................',
  '................',
  '................',
  '................',
],{y:'#d89800',x:'#2d1b00',o:'#f5a020'});

// ── Character 03: グリズリー (Grizzly) ────────────────────────────────────────
const C03S = g([
  '.....aa..aa.....',
  '.....aa..aa.....',
  '....aaaaaaaa....',
  '....aaxaaxaa....',
  '....aaaraaaaaa..',
  '....aaaaaaaa....',
  '.....aaaaaa.....',
  '...ddaaaaaaddd..',
  '...ddaaaaaaddd..',
  '....daaaaaad....',
  '.....aa..aa.....',
  '.....aa..aa.....',
  '....eee..eee....',
  '................',
  '................',
  '................',
],{a:'#b87840',d:'#d49860',e:'#a06030',x:'#2d1b00',r:'#ff6b6b'});
const C03C = g([
  '.....bb..bb.....',
  '.....bb..bb.....',
  '...bbbbbbbbbb...',
  '...bbxbbxbbbb...',
  '...bbbrbbbbbb...',
  '...bbbbbbbbbb...',
  '....bbbbbbbb....',
  '..dddbbbbbbddd..',
  '..dddbbbbbbddd..',
  '...ddbbbbbbdd...',
  '.....bbb.bbb....',
  '.....bbb.bbb....',
  '...eeee..eeee...',
  '................',
  '................',
  '................',
],{b:'#985820',d:'#d49860',e:'#a06030',x:'#2d1b00',r:'#ff6b6b'});
const C03F = g([
  '.....cc..cc.....',
  '.....cc..cc.....',
  '..cccccccccccc..',
  '..ccxcccxccccc..',
  '..cccrccccccc...',
  '..cccccccccccc..',
  '..cccccccccccc..',
  '..cccccccccccc..',
  '.ccccccccccccc..',
  '..cccccccccccc..',
  '....ccc..ccc....',
  '....ccc..ccc....',
  '...eeeeeeeeee...',
  '................',
  '................',
  '................',
],{c:'#784008',e:'#a06030',x:'#2d1b00',r:'#ff6b6b'});

// ── Character 04: グレーねこ (Gray Cat) ───────────────────────────────────────
const C04S = g([
  '....a......a....',
  '.....aaaaaa.....',
  '....aaaaaaaa....',
  '....aaxaaxaa....',
  '....aaaxaaaa....',
  '....aaaaaaaa....',
  '.....aaaaaa.....',
  '...ddaaaaaddd...',
  '...ddaaaaaddd...',
  '....daaaaad.....',
  '.....aa..aa.....',
  '.....aa..aa.....',
  '....eee..eee....',
  '................',
  '................',
  '................',
],{a:'#c0c0c8',d:'#d8d8e0',e:'#b0b0b8',x:'#2d1b00',r:'#ff6b6b'});
const C04C = g([
  '....b......b....',
  '....bbbbbbbb....',
  '...bbbbbbbbbb...',
  '...bbxbbxbbbb...',
  '...bbbrbbbbbbb..',
  '...bbbbbbbbbb...',
  '....bbbbbbbb....',
  '..dddbbbbbbbddd.',
  '..dddbbbbbbbddd.',
  '...ddbbbbbddd...',
  '.....bbb.bbb....',
  '.....bbb.bbb....',
  '...eeee..eeee...',
  '................',
  '................',
  '................',
],{b:'#a0a0a8',d:'#d8d8e0',e:'#b0b0b8',x:'#2d1b00',r:'#ff6b6b'});
const C04F = g([
  '....c......c....',
  '...cccccccccc...',
  '..cccccccccccc..',
  '..ccxcccxccccc..',
  '..cccrccccccc...',
  '..cccccccccccc..',
  '..cccccccccccc..',
  '..cccccccccccc..',
  '.ccccccccccccc..',
  '..cccccccccccc..',
  '....ccc..ccc....',
  '....ccc..ccc....',
  '...eeeeeeeeee...',
  '................',
  '................',
  '................',
],{c:'#808088',e:'#b0b0b8',x:'#2d1b00',r:'#ff6b6b'});

// ── Character 05: しろやぎ (White Goat) ───────────────────────────────────────
const C05S = g([
  '....f......f....',
  '....faaaaafa....',
  '....aaaaaaaa....',
  '....aaxaaxaa....',
  '....aaaxaaaa....',
  '....aaaaaaaa....',
  '.....aaaaaa.....',
  '...ddaaaaaddd...',
  '...ddaaaaaddd...',
  '....daaaaad.....',
  '.....aa..aa.....',
  '.....aa..aa.....',
  '....eee..eee....',
  '................',
  '................',
  '................',
],{a:'#f0ece0',d:'#e8e4d8',e:'#d0c8b0',f:'#c8c0a8',x:'#2d1b00',r:'#ff6b6b'});
const C05C = g([
  '....f......f....',
  '....fbbbbbbf....',
  '...bbbbbbbbbb...',
  '...bbxbbxbbbb...',
  '...bbbrbbbbbbb..',
  '...bbbbbbbbbb...',
  '....bbbbbbbb....',
  '..dddbbbbbbddd..',
  '..dddbbbbbbddd..',
  '...ddbbbbbbdd...',
  '.....bbb.bbb....',
  '.....bbb.bbb....',
  '...eeee..eeee...',
  '................',
  '................',
  '................',
],{b:'#d8d0b8',d:'#e8e4d8',e:'#d0c8b0',f:'#c8c0a8',x:'#2d1b00',r:'#ff6b6b'});
const C05F = g([
  '....f......f....',
  '....fccccccf....',
  '..cccccccccccc..',
  '..ccxcccxccccc..',
  '..cccrccccccc...',
  '..cccccccccccc..',
  '..cccccccccccc..',
  '..cccccccccccc..',
  '.ccccccccccccc..',
  '..cccccccccccc..',
  '....ccc..ccc....',
  '....ccc..ccc....',
  '...eeeeeeeeee...',
  '................',
  '................',
  '................',
],{c:'#c0b098',e:'#d0c8b0',f:'#c8c0a8',x:'#2d1b00',r:'#ff6b6b'});

// ── Character 06: いぬ (Dog) ──────────────────────────────────────────────────
const C06S = g([
  '................',
  '.....aaaaaa.....',
  '..ffaaaaaaaff...',
  '..ffaaxaaxaff...',
  '..ffaaaxaaff....',
  '..ffaaaaaaaff...',
  '.....aaaaaa.....',
  '...ddaaaaaddd...',
  '...ddaaaaaddd...',
  '....daaaaad.....',
  '.....aa..aa.....',
  '.....aa..aa.....',
  '....eee..eee....',
  '................',
  '................',
  '................',
],{a:'#d4a050',d:'#e8c070',e:'#c8a040',f:'#c88830',x:'#2d1b00',r:'#ff6b6b'});
const C06C = g([
  '................',
  '....bbbbbbbb....',
  '..ffbbbbbbbbff..',
  '..ffbbxbbxbbff..',
  '..ffbbbrbbbff...',
  '..ffbbbbbbbbff..',
  '....bbbbbbbb....',
  '..dddbbbbbbddd..',
  '..dddbbbbbbddd..',
  '...ddbbbbbbdd...',
  '.....bbb.bbb....',
  '.....bbb.bbb....',
  '...eeee..eeee...',
  '................',
  '................',
  '................',
],{b:'#b88030',d:'#e8c070',e:'#c8a040',f:'#9c6820',x:'#2d1b00',r:'#ff6b6b'});
const C06F = g([
  '................',
  '...cccccccccc...',
  '..ffccccccccff..',
  '..ffccxcccxff...',
  '..ffcccrcccff...',
  '..ffccccccccff..',
  '..cccccccccccc..',
  '..cccccccccccc..',
  '.ccccccccccccc..',
  '..cccccccccccc..',
  '....ccc..ccc....',
  '....ccc..ccc....',
  '...eeeeeeeeee...',
  '................',
  '................',
  '................',
],{c:'#9c6820',e:'#c8a040',f:'#784010',x:'#2d1b00',r:'#ff6b6b'});

// ── Character 07: うさぎ (Bunny) ──────────────────────────────────────────────
const C07S = g([
  '.....ai..ia.....',
  '.....ai..ia.....',
  '.....ai..ia.....',
  '....aaaaaaaa....',
  '....aaxaaxaa....',
  '....aaaxaaaa....',
  '.....aaaaaa.....',
  '...ddaaaaaddd...',
  '...ddaaaaaddd...',
  '....daaaaad.....',
  '.....aa..aa.....',
  '.....aa..aa.....',
  '....eee..eee....',
  '................',
  '................',
  '................',
],{a:'#ffb7d5',i:'#ffd4e8',d:'#ffd0e8',e:'#f0b0c8',x:'#2d1b00',r:'#ff6b6b'});
const C07C = g([
  '.....bi..ib.....',
  '.....bi..ib.....',
  '.....bi..ib.....',
  '...bbbbbbbbbb...',
  '...bbxbbxbbbb...',
  '...bbbrbbbbbbb..',
  '....bbbbbbbb....',
  '..dddbbbbbbbddd.',
  '..dddbbbbbbbddd.',
  '...ddbbbbbddd...',
  '.....bbb.bbb....',
  '.....bbb.bbb....',
  '...eeee..eeee...',
  '................',
  '................',
  '................',
],{b:'#e898b8',i:'#ffd4e8',d:'#ffd0e8',e:'#f0b0c8',x:'#2d1b00',r:'#ff6b6b'});
const C07F = g([
  '.....ci..ic.....',
  '.....ci..ic.....',
  '.....ci..ic.....',
  '..cccccccccccc..',
  '..ccxcccxccccc..',
  '..cccrccccccc...',
  '..cccccccccccc..',
  '..cccccccccccc..',
  '.ccccccccccccc..',
  '..cccccccccccc..',
  '....ccc..ccc....',
  '....ccc..ccc....',
  '...eeeeeeeeee...',
  '................',
  '................',
  '................',
],{c:'#d07898',i:'#ffd4e8',e:'#f0b0c8',x:'#2d1b00',r:'#ff6b6b'});

// ── Character 08: ドラゴン (Dragon) ───────────────────────────────────────────
const C08S = g([
  '....afa.afa.....',
  '...afafaafaf....',
  '....aaaaaaaa....',
  '....aaxaaxaa....',
  '....aaaxaaaa....',
  '....aaaaaaaa....',
  '.....aaaaaa.....',
  '...ddaaaaaddd...',
  '...ddaaaaaddd...',
  '....daaaaad.....',
  '.....aa..aa.....',
  '.....aa..aa.....',
  '....eee..eee....',
  '................',
  '................',
  '................',
],{a:'#60d8c8',d:'#80e8d8',e:'#50c0b0',f:'#f8d040',x:'#2d1b00',r:'#ff6b6b'});
const C08C = g([
  '....bfb.bfb.....',
  '...bfbfbbfbf....',
  '...bbbbbbbbbb...',
  '...bbxbbxbbbb...',
  '...bbbrbbbbbbb..',
  '...bbbbbbbbbb...',
  '....bbbbbbbb....',
  '..dddbbbbbbddd..',
  '..dddbbbbbbddd..',
  '...ddbbbbbbdd...',
  '.....bbb.bbb....',
  '.....bbb.bbb....',
  '...eeee..eeee...',
  '................',
  '................',
  '................',
],{b:'#40b8a8',d:'#80e8d8',e:'#50c0b0',f:'#f8d040',x:'#2d1b00',r:'#ff6b6b'});
const C08F = g([
  '....cfc.cfc.....',
  '...cfcfccfcf....',
  '..cccccccccccc..',
  '..ccxcccxccccc..',
  '..cccrccccccc...',
  '..cccccccccccc..',
  '..cccccccccccc..',
  '..cccccccccccc..',
  '.ccccccccccccc..',
  '..cccccccccccc..',
  '....ccc..ccc....',
  '....ccc..ccc....',
  '...eeeeeeeeee...',
  '................',
  '................',
  '................',
],{c:'#208888',e:'#50c0b0',f:'#f8d040',x:'#2d1b00',r:'#ff6b6b'});

// ── Character 09: スポーツ (Sports) ───────────────────────────────────────────
const C09S = g([
  '................',
  '.....aaaaaa.....',
  '....ffffffff....',
  '....aaxaaxaa....',
  '....aaaxaaaa....',
  '....aaaaaaaa....',
  '.....aaaaaa.....',
  '...ddaaaaaddd...',
  '...ddaaaaaddd...',
  '....daaaaad.....',
  '.....aa..aa.....',
  '.....aa..aa.....',
  '....eee..eee....',
  '................',
  '................',
  '................',
],{a:'#5090e0',d:'#70b8f0',e:'#4898d8',f:'#ffffff',x:'#2d1b00',r:'#ff6b6b'});
const C09C = g([
  '................',
  '....bbbbbbbb....',
  '...fffffffff....',
  '...bbxbbxbbbb...',
  '...bbbrbbbbbbb..',
  '...bbbbbbbbbb...',
  '....bbbbbbbb....',
  '..dddbbbbbbddd..',
  '..dddbbbbbbddd..',
  '...ddbbbbbbdd...',
  '.....bbb.bbb....',
  '.....bbb.bbb....',
  '...eeee..eeee...',
  '................',
  '................',
  '................',
],{b:'#3070c8',d:'#70b8f0',e:'#4898d8',f:'#ffffff',x:'#2d1b00',r:'#ff6b6b'});
const C09F = g([
  '................',
  '...cccccccccc...',
  '..fffffffffff...',
  '..ccxcccxccccc..',
  '..cccrccccccc...',
  '..cccccccccccc..',
  '..cccccccccccc..',
  '..cccccccccccc..',
  '.ccccccccccccc..',
  '..cccccccccccc..',
  '....ccc..ccc....',
  '....ccc..ccc....',
  '...eeeeeeeeee...',
  '................',
  '................',
  '................',
],{c:'#1850a8',e:'#4898d8',f:'#ffffff',x:'#2d1b00',r:'#ff6b6b'});

// ── Character 10: にんじゃ (Ninja) ────────────────────────────────────────────
const C10S = g([
  '................',
  '.....aaaaaa.....',
  '....rrrrrrrr....',
  '....aaxaaxaa....',
  '....ssssssss....',
  '....ssssssss....',
  '.....aaaaaa.....',
  '...ddaaaaaddd...',
  '...ddaaaaaddd...',
  '....daaaaad.....',
  '.....aa..aa.....',
  '.....aa..aa.....',
  '....eee..eee....',
  '................',
  '................',
  '................',
],{a:'#484848',d:'#606060',e:'#303030',r:'#c03030',s:'#303030',x:'#2d1b00'});
const C10C = g([
  '................',
  '....bbbbbbbb....',
  '...rrrrrrrrrr...',
  '...bbxbbxbbbb...',
  '...ssssssssss...',
  '...ssssssssss...',
  '....bbbbbbbb....',
  '..dddbbbbbbbddd.',
  '..dddbbbbbbbddd.',
  '...ddbbbbbddd...',
  '.....bbb.bbb....',
  '.....bbb.bbb....',
  '...eeee..eeee...',
  '................',
  '................',
  '................',
],{b:'#303030',d:'#606060',e:'#303030',r:'#c03030',s:'#202020',x:'#2d1b00'});
const C10F = g([
  '................',
  '...cccccccccc...',
  '..rrrrrrrrrrrr..',
  '..ccxcccxccccc..',
  '..ssssssssssss..',
  '..ssssssssssss..',
  '..cccccccccccc..',
  '..cccccccccccc..',
  '.ccccccccccccc..',
  '..cccccccccccc..',
  '....ccc..ccc....',
  '....ccc..ccc....',
  '...eeeeeeeeee...',
  '................',
  '................',
  '................',
],{c:'#202020',e:'#303030',r:'#c03030',s:'#181818',x:'#2d1b00'});

// ── Character 11: マッスル (Muscle) ───────────────────────────────────────────
const C11S = g([
  '................',
  '.....aaaaaa.....',
  '....ffffffff....',
  '....aaxaaxaa....',
  '....aaaxaaaa....',
  '....aaaaaaaa....',
  '.....aaaaaa.....',
  '...ddaaaaaddd...',
  '...ddaaaaaddd...',
  '....daaaaad.....',
  '.....aa..aa.....',
  '.....aa..aa.....',
  '....eee..eee....',
  '................',
  '................',
  '................',
],{a:'#e8a858',d:'#4888e0',e:'#2868c0',f:'#5599ee',x:'#2d1b00',r:'#ff6b6b'});
const C11C = g([
  '................',
  '....bbbbbbbb....',
  '...fffffffff....',
  '...bbxbbxbbbb...',
  '...bbbrbbbbbbb..',
  '...bbbbbbbbbb...',
  '....bbbbbbbb....',
  '..dddbbbbbbddd..',
  '..dddbbbbbbddd..',
  '...ddbbbbbbdd...',
  '.....bbb.bbb....',
  '.....bbb.bbb....',
  '...eeee..eeee...',
  '................',
  '................',
  '................',
],{b:'#d08838',d:'#4888e0',e:'#2868c0',f:'#5599ee',x:'#2d1b00',r:'#ff6b6b'});
const C11F = g([
  '................',
  '...cccccccccc...',
  '..fffffffffff...',
  '..ccxcccxccccc..',
  '..cccrccccccc...',
  '..cccccccccccc..',
  '..cccccccccccc..',
  '..cccccccccccc..',
  '.ccccccccccccc..',
  '..cccccccccccc..',
  '....ccc..ccc....',
  '....ccc..ccc....',
  '...eeeeeeeeee...',
  '................',
  '................',
  '................',
],{c:'#b86820',e:'#2868c0',f:'#5599ee',x:'#2d1b00',r:'#ff6b6b'});

// ── Character 12: クール (Cool) ───────────────────────────────────────────────
const C12S = g([
  '................',
  '.....aaaaaa.....',
  '....aaaaaaaa....',
  '....ssssssss....',
  '....ssssssss....',
  '....aaaaaaaa....',
  '.....aaaaaa.....',
  '...ddaaaaaddd...',
  '...ddaaaaaddd...',
  '....daaaaad.....',
  '.....aa..aa.....',
  '.....aa..aa.....',
  '....eee..eee....',
  '................',
  '................',
  '................',
],{a:'#d4a068',d:'#888880',e:'#606058',s:'#303030',x:'#2d1b00',r:'#ff6b6b'});
const C12C = g([
  '................',
  '....bbbbbbbb....',
  '...bbbbbbbbbb...',
  '...ssssssssss...',
  '...ssssssssss...',
  '...bbbbbbbbbb...',
  '....bbbbbbbb....',
  '..dddbbbbbbddd..',
  '..dddbbbbbbddd..',
  '...ddbbbbbbdd...',
  '.....bbb.bbb....',
  '.....bbb.bbb....',
  '...eeee..eeee...',
  '................',
  '................',
  '................',
],{b:'#b88048',d:'#888880',e:'#606058',s:'#303030',x:'#2d1b00',r:'#ff6b6b'});
const C12F = g([
  '................',
  '...cccccccccc...',
  '..cccccccccccc..',
  '..ssssssssssss..',
  '..ssssssssssss..',
  '..cccccccccccc..',
  '..cccccccccccc..',
  '..cccccccccccc..',
  '.ccccccccccccc..',
  '..cccccccccccc..',
  '....ccc..ccc....',
  '....ccc..ccc....',
  '...eeeeeeeeee...',
  '................',
  '................',
  '................',
],{c:'#9c6030',e:'#606058',s:'#303030',x:'#2d1b00',r:'#ff6b6b'});

// ── Character 13: ほのお (Fire) ───────────────────────────────────────────────
const C13S = g([
  '......y.........',
  '.....yyy........',
  '....yyyyy.......',
  '...aayyyy.......',
  '..aaaxaaxa......',
  '..aaaaaaaa......',
  '..aaaaaaaaa.....',
  '.aaaaaaaaaaa....',
  '.aaaaaaaaaaa....',
  '..aaaaaaaaaaa...',
  '..aaabaabaaa....',
  '...aaaaaaaaa....',
  '....aaaaaaa.....',
  '................',
  '................',
  '................',
],{a:'#ff7020',b:'#e85000',y:'#f8c020',x:'#2d1b00'});
const C13C = g([
  '......y.........',
  '.....yyy........',
  '....yyyyy.......',
  '..aaaaayyy......',
  '..aaaxaaxa......',
  '..aaaaaaaaa.....',
  '..aaaaaaaaaaa...',
  '.aaaaaaaaaaaa...',
  '.aaaaaaaaaaaa...',
  '..aaaaaaaaaaaa..',
  '...aaabaabaaa...',
  '....aaaaaaaaaa..',
  '.....aaaaaaaa...',
  '................',
  '................',
  '................',
],{a:'#e85000',b:'#cc3000',y:'#f8c020',x:'#2d1b00'});
const C13F = g([
  '......y.........',
  '.....yyy........',
  '....yyyyy.......',
  '...aaaayyyy.....',
  '..aaaaaxaaxa....',
  '..aaaaaaaaaaaa..',
  '..aaaaaaaaaaaaa.',
  '.aaaaaaaaaaaaaa.',
  '.aaaaaaaaaaaaaa.',
  '..aaaaaaaaaaaa..',
  '...aaabaabaaa...',
  '....aaaaaaaaaaa.',
  '.....aaaaaaaaa..',
  '................',
  '................',
  '................',
],{a:'#cc3000',b:'#aa1000',y:'#f8c020',x:'#2d1b00'});

// ── Character 14: みずたま (Water Drop) ───────────────────────────────────────
const C14S = g([
  '......a.........',
  '.....aaa........',
  '....aaaaa.......',
  '....aaaaa.......',
  '...aaaxaxa......',
  '...aaaaaaa......',
  '..aaaaaaaaa.....',
  '..aaaaaaaaa.....',
  '..aaaaaaaaa.....',
  '..haaaaaah......',
  '...aaaaaaa......',
  '....aaaaa.......',
  '................',
  '................',
  '................',
  '................',
],{a:'#78c8f0',h:'#a0e0f8',x:'#2d1b00',r:'#ff6b6b'});
const C14C = g([
  '......b.........',
  '.....bbb........',
  '....bbbbb.......',
  '...bbbbbbb......',
  '...bbxbxbb......',
  '...bbbbbbb......',
  '..bbbbbbbbb.....',
  '..bbbbbbbbb.....',
  '..bbbbbbbbb.....',
  '..hbbbbbhbb.....',
  '...bbbbbbb......',
  '....bbbbb.......',
  '.....bbb........',
  '................',
  '................',
  '................',
],{b:'#50a8d8',h:'#a0e0f8',x:'#2d1b00',r:'#ff6b6b'});
const C14F = g([
  '......c.........',
  '.....ccc........',
  '....ccccc.......',
  '...ccccccc......',
  '..cccxcxccc.....',
  '..ccccccccc.....',
  '..ccccccccccc...',
  '..ccccccccccc...',
  '.cccccccccccc...',
  '..hcccccccccc...',
  '...ccccccccc....',
  '....ccccccc.....',
  '.....ccccc......',
  '................',
  '................',
  '................',
],{c:'#3088b8',h:'#a0e0f8',x:'#2d1b00',r:'#ff6b6b'});

// ── Character 15: めばえ (Sprout) ─────────────────────────────────────────────
const C15S = g([
  '.......f........',
  '......fff.......',
  '.....fffff......',
  '....aaaaaaa.....',
  '....aaxaaxa.....',
  '....aaaaaaa.....',
  '....aaaaaaa.....',
  '...aaaaaaaaa....',
  '...aaaaaaaaa....',
  '....aaaaaaa.....',
  '.....aa..aa.....',
  '.....aa..aa.....',
  '....eee..eee....',
  '................',
  '................',
  '................',
],{a:'#88cc50',e:'#70b840',f:'#60aa28',x:'#2d1b00',r:'#ff6b6b'});
const C15C = g([
  '.......f........',
  '......fff.......',
  '.....fffff......',
  '...bbbbbbbbb....',
  '...bbxbbxbbb....',
  '...bbbbbbbbb....',
  '...bbbbbbbbb....',
  '..bbbbbbbbbbb...',
  '..bbbbbbbbbbb...',
  '...bbbbbbbbb....',
  '.....bbb.bbb....',
  '.....bbb.bbb....',
  '...eeee..eeee...',
  '................',
  '................',
  '................',
],{b:'#60aa28',e:'#70b840',f:'#408810',x:'#2d1b00',r:'#ff6b6b'});
const C15F = g([
  '.......f........',
  '......fff.......',
  '.....fffff......',
  '..ccccccccccc...',
  '..ccxcccxcccc...',
  '..ccccccccccc...',
  '..ccccccccccc...',
  '..ccccccccccc...',
  '.cccccccccccc...',
  '..ccccccccccc...',
  '....ccc..ccc....',
  '....ccc..ccc....',
  '...eeeeeeeeee...',
  '................',
  '................',
  '................',
],{c:'#408810',e:'#70b840',f:'#206000',x:'#2d1b00',r:'#ff6b6b'});

// ── Character 16: ロボ (Robot) ────────────────────────────────────────────────
const C16S = g([
  '......f.........',
  '.....aaa........',
  '....aaaaaaaa....',
  '....assssssaa...',
  '....asxssxsaa...',
  '....assssssaa...',
  '....aaaaaaaa....',
  '...ddaaaaaddd...',
  '...ddaaaaaddd...',
  '....daaaaad.....',
  '.....aa..aa.....',
  '.....aa..aa.....',
  '....eee..eee....',
  '................',
  '................',
  '................',
],{a:'#a0a8b8',d:'#c0c8d8',e:'#909898',f:'#808898',s:'#202830',x:'#40cc80',r:'#ff6b6b'});
const C16C = g([
  '......f.........',
  '.....bbb........',
  '...bbbbbbbbbb...',
  '...bssssssbb....',
  '...bsxssxsbb....',
  '...bssssssbb....',
  '...bbbbbbbbbb...',
  '..dddbbbbbbddd..',
  '..dddbbbbbbddd..',
  '...ddbbbbbbdd...',
  '.....bbb.bbb....',
  '.....bbb.bbb....',
  '...eeee..eeee...',
  '................',
  '................',
  '................',
],{b:'#808898',d:'#c0c8d8',e:'#909898',f:'#606878',s:'#202830',x:'#40cc80',r:'#ff6b6b'});
const C16F = g([
  '......f.........',
  '.....ccc........',
  '..cccccccccccc..',
  '..cssssssscc....',
  '..csxssxsscc....',
  '..cssssssscc....',
  '..cccccccccccc..',
  '..cccccccccccc..',
  '.ccccccccccccc..',
  '..cccccccccccc..',
  '....ccc..ccc....',
  '....ccc..ccc....',
  '...eeeeeeeeee...',
  '................',
  '................',
  '................',
],{c:'#606878',e:'#909898',f:'#404858',s:'#202830',x:'#40cc80',r:'#ff6b6b'});

// ── Character 17: まほう (Magic Blob) ─────────────────────────────────────────
const C17S = g([
  '......f.f.......',
  '................',
  '....aaaaaaaa....',
  '...aaaaaaaaaa...',
  '...aaxaaaaxa....',
  '...aaaraaaaaa...',
  '...aaaaaaaaaa...',
  '...aaaaaaaaaa...',
  '....aaaaaaaa....',
  '....aaaaaaaa....',
  '.....aa..aa.....',
  '.....aa..aa.....',
  '....eee..eee....',
  '................',
  '................',
  '................',
],{a:'#c070e8',e:'#b870d8',f:'#f8a0ff',x:'#2d1b00',r:'#ff6b6b'});
const C17C = g([
  '......f.f.......',
  '................',
  '...bbbbbbbbbb...',
  '..bbbbbbbbbbbb..',
  '..bbxbbbbxbbbb..',
  '..bbbrbbbbbbb...',
  '..bbbbbbbbbbbb..',
  '..bbbbbbbbbbbb..',
  '...bbbbbbbbbb...',
  '....bbbbbbbb....',
  '.....bbb.bbb....',
  '.....bbb.bbb....',
  '...eeee..eeee...',
  '................',
  '................',
  '................',
],{b:'#a050d0',e:'#b870d8',f:'#f8a0ff',x:'#2d1b00',r:'#ff6b6b'});
const C17F = g([
  '......f.f.......',
  '................',
  '..cccccccccccc..',
  '.cccccccccccccc.',
  '.ccxcccccxcccc..',
  '.cccrcccccccc...',
  '.cccccccccccccc.',
  '.cccccccccccccc.',
  '..cccccccccccc..',
  '...cccccccccc...',
  '....ccc..ccc....',
  '....ccc..ccc....',
  '...eeeeeeeeee...',
  '................',
  '................',
  '................',
],{c:'#8030b8',e:'#b870d8',f:'#f8a0ff',x:'#2d1b00',r:'#ff6b6b'});

// ── Character 18: かいぞく (Pirate) ───────────────────────────────────────────
const C18S = g([
  '...hhhhhhhh.....',
  '....hhphhhh.....',
  '....aaaaaaaa....',
  '....aaxaaxaa....',
  '....aaaxaaaa....',
  '....aaaaaaaa....',
  '.....aaaaaa.....',
  '...ddaaaaaddd...',
  '...ddaaaaaddd...',
  '....daaaaad.....',
  '.....aa..aa.....',
  '.....aa..aa.....',
  '....eee..eee....',
  '................',
  '................',
  '................',
],{a:'#c89050',d:'#a87030',e:'#604030',h:'#202020',p:'#f8f8f8',x:'#2d1b00',r:'#ff6b6b'});
const C18C = g([
  '...hhhhhhhhhh...',
  '....hhphhhhh....',
  '...bbbbbbbbbb...',
  '...bbxbbxbbbb...',
  '...bbbrbbbbbbb..',
  '...bbbbbbbbbb...',
  '....bbbbbbbb....',
  '..dddbbbbbbddd..',
  '..dddbbbbbbddd..',
  '...ddbbbbbbdd...',
  '.....bbb.bbb....',
  '.....bbb.bbb....',
  '...eeee..eeee...',
  '................',
  '................',
  '................',
],{b:'#a87030',d:'#c89050',e:'#604030',h:'#202020',p:'#f8f8f8',x:'#2d1b00',r:'#ff6b6b'});
const C18F = g([
  '..hhhhhhhhhhhh..',
  '...hhphhhhhh....',
  '..cccccccccccc..',
  '..ccxcccxccccc..',
  '..cccrccccccc...',
  '..cccccccccccc..',
  '..cccccccccccc..',
  '..cccccccccccc..',
  '.ccccccccccccc..',
  '..cccccccccccc..',
  '....ccc..ccc....',
  '....ccc..ccc....',
  '...eeeeeeeeee...',
  '................',
  '................',
  '................',
],{c:'#8c5818',e:'#604030',h:'#202020',p:'#f8f8f8',x:'#2d1b00',r:'#ff6b6b'});

// ── Character 19: てんし (Angel) ──────────────────────────────────────────────
const C19S = g([
  '.....hhhhh......',
  '....h.....h.....',
  '....aaaaaaaa....',
  '....aaxaaxaa....',
  '....aaaxaaaa....',
  '....aaaaaaaa....',
  '.....aaaaaa.....',
  '.wwddaaaaadddww.',
  '.wwddaaaaadddww.',
  '.w..daaaaad..w..',
  '.....aa..aa.....',
  '.....aa..aa.....',
  '....eee..eee....',
  '................',
  '................',
  '................',
],{a:'#f8f0e0',d:'#e8d8c0',e:'#b0d0e8',h:'#f8d020',w:'#d0e8f8',x:'#2d1b00',r:'#ff6b6b'});
const C19C = g([
  '.....hhhhh......',
  '....h.....h.....',
  '...bbbbbbbbbb...',
  '...bbxbbxbbbb...',
  '...bbbrbbbbbbb..',
  '...bbbbbbbbbb...',
  '....bbbbbbbb....',
  '.wwddbbbbbbdddww',
  '.wwddbbbbbbdddww',
  '.w..dbbbbbbdd.w.',
  '.....bbb.bbb....',
  '.....bbb.bbb....',
  '...eeee..eeee...',
  '................',
  '................',
  '................',
],{b:'#e8d8c0',d:'#d8c8b0',e:'#b0d0e8',h:'#f8d020',w:'#d0e8f8',x:'#2d1b00',r:'#ff6b6b'});
const C19F = g([
  '.....hhhhh......',
  '....h.....h.....',
  '..cccccccccccc..',
  '..ccxcccxccccc..',
  '..cccrccccccc...',
  '..cccccccccccc..',
  '..cccccccccccc..',
  'wwccccccccccccww',
  'wwccccccccccccww',
  'ww.cccccccccc.ww',
  '....ccc..ccc....',
  '....ccc..ccc....',
  '...eeeeeeeeee...',
  '................',
  '................',
  '................',
],{c:'#d8c0a0',e:'#b0d0e8',h:'#f8d020',w:'#d0e8f8',x:'#2d1b00',r:'#ff6b6b'});

// ── Character 20: おうさま (King) ─────────────────────────────────────────────
const C20S = g([
  '....fgfgfgf.....',
  '.....fffff......',
  '....aaaaaaaa....',
  '....aaxaaxaa....',
  '....aaaxaaaa....',
  '....aaaaaaaa....',
  '....caaaaac.....',
  '...ccdaaadcc....',
  '...ccdaaadcc....',
  '....cdaaadc.....',
  '.....aa..aa.....',
  '.....aa..aa.....',
  '....eee..eee....',
  '................',
  '................',
  '................',
],{a:'#f0c030',c:'#e03020',d:'#f8f8f8',e:'#c08000',f:'#f8e040',g:'#f0c030',x:'#2d1b00',r:'#ff6b6b'});
const C20C = g([
  '....fgfgfgf.....',
  '.....fffff......',
  '...bbbbbbbbbb...',
  '...bbxbbxbbbb...',
  '...bbbrbbbbbbb..',
  '...bbbbbbbbbb...',
  '...cbbbbbbbc....',
  '..ccdbbbbbbdcc..',
  '..ccdbbbbbbdcc..',
  '...cdbbbbbbdc...',
  '.....bbb.bbb....',
  '.....bbb.bbb....',
  '...eeee..eeee...',
  '................',
  '................',
  '................',
],{b:'#e0a010',c:'#e03020',d:'#f8f8f8',e:'#c08000',f:'#f8e040',g:'#f0c030',x:'#2d1b00',r:'#ff6b6b'});
const C20F = g([
  '....fgfgfgf.....',
  '.....fffff......',
  '..cccccccccccc..',
  '..ccxcccxccccc..',
  '..cccrccccccc...',
  '..cccccccccccc..',
  '..kcccccccccck..',
  '..kkcccccccckkk.',
  '.kkkcccccccckkk.',
  '..kkcccccccckkk.',
  '....ccc..ccc....',
  '....ccc..ccc....',
  '...eeeeeeeeee...',
  '................',
  '................',
  '................',
],{c:'#c08000',e:'#c08000',f:'#f8e040',g:'#f0c030',k:'#e03020',x:'#2d1b00',r:'#ff6b6b'});

// ── Interface & CHARACTERS ────────────────────────────────────────────────────

export interface CharacterDef {
  id: string;
  name: string;
  emoji: string;
  description: string;
  colorMap: Record<string, string>;
  unlockId?: string;
  customGrids?: { slim: Grid; chubby: Grid; fat: Grid };
}

export const CHARACTERS: CharacterDef[] = [
  // ── スターター 3体 (colorMapのみ) ──────────────────────────────────────────
  { id:'yagi', name:'やぎ', emoji:'🐐',
    description:'ゼロからビジネスを目指す熱いやぎ', colorMap:{} },
  { id:'neko', name:'ねこ', emoji:'🐱',
    description:'のんびりやだけど実はがんばるねこ',
    colorMap:{ [S]:'#ffb7c5',[F]:'#e8829a',[T]:'#d4607a',[B]:'#ffd4e8',[G]:'#ff9eb5' } },
  { id:'kuma', name:'くま', emoji:'🐻',
    description:'のしのし歩くマイペースなくま',
    colorMap:{ [S]:'#c8a878',[F]:'#b08858',[T]:'#906840',[B]:'#d4b896',[G]:'#785030' } },

  // ── アンロック 20体 (customGrids) ─────────────────────────────────────────
  { id:'char01', name:'ねむり',    emoji:'😴', unlockId:'first_record',
    description:'zzz… いつでも眠そうなのんびり屋',
    colorMap:{}, customGrids:{ slim:C01S, chubby:C01C, fat:C01F } },
  { id:'char02', name:'ひよこ',    emoji:'🐤', unlockId:'streak3',
    description:'ピヨピヨ！元気いっぱいのひよこ',
    colorMap:{}, customGrids:{ slim:C02S, chubby:C02C, fat:C02F } },
  { id:'char03', name:'グリズリー',emoji:'🐻', unlockId:'streak7',
    description:'どっしり構えた頼もしいグリズリー',
    colorMap:{}, customGrids:{ slim:C03S, chubby:C03C, fat:C03F } },
  { id:'char04', name:'グレーねこ',emoji:'🩶', unlockId:'streak14',
    description:'クールでミステリアスなグレーねこ',
    colorMap:{}, customGrids:{ slim:C04S, chubby:C04C, fat:C04F } },
  { id:'char05', name:'しろやぎ',  emoji:'🐑', unlockId:'log5',
    description:'ふわふわやさしいしろやぎ',
    colorMap:{}, customGrids:{ slim:C05S, chubby:C05C, fat:C05F } },
  { id:'char06', name:'いぬ',      emoji:'🐶', unlockId:'log10',
    description:'べろべろ忠実でかわいいわんこ',
    colorMap:{}, customGrids:{ slim:C06S, chubby:C06C, fat:C06F } },
  { id:'char07', name:'うさぎ',    emoji:'🐰', unlockId:'log30',
    description:'ぴょんぴょんすばしっこいうさぎ',
    colorMap:{}, customGrids:{ slim:C07S, chubby:C07C, fat:C07F } },
  { id:'char08', name:'ドラゴン',  emoji:'🐲', unlockId:'streak30',
    description:'かっこいい小さなドラゴン',
    colorMap:{}, customGrids:{ slim:C08S, chubby:C08C, fat:C08F } },
  { id:'char09', name:'スポーツ',  emoji:'⚽', unlockId:'mission5',
    description:'いつでも全力！スポーツマン',
    colorMap:{}, customGrids:{ slim:C09S, chubby:C09C, fat:C09F } },
  { id:'char10', name:'にんじゃ',  emoji:'🥷', unlockId:'mission10',
    description:'影から見守るストイックなにんじゃ',
    colorMap:{}, customGrids:{ slim:C10S, chubby:C10C, fat:C10F } },
  { id:'char11', name:'マッスル',  emoji:'💪', unlockId:'steps100k',
    description:'筋トレ大好きマッスルマン',
    colorMap:{}, customGrids:{ slim:C11S, chubby:C11C, fat:C11F } },
  { id:'char12', name:'クール',    emoji:'😎', unlockId:'log50',
    description:'サングラスがトレードマークのクール野郎',
    colorMap:{}, customGrids:{ slim:C12S, chubby:C12C, fat:C12F } },
  { id:'char13', name:'ほのお',    emoji:'🔥', unlockId:'mission20',
    description:'燃え上がる情熱のほのお',
    colorMap:{}, customGrids:{ slim:C13S, chubby:C13C, fat:C13F } },
  { id:'char14', name:'みずたま',  emoji:'💧', unlockId:'steps500k',
    description:'さらさら流れるみずたま',
    colorMap:{}, customGrids:{ slim:C14S, chubby:C14C, fat:C14F } },
  { id:'char15', name:'めばえ',    emoji:'🌱', unlockId:'goal',
    description:'少しずつ成長するめばえ',
    colorMap:{}, customGrids:{ slim:C15S, chubby:C15C, fat:C15F } },
  { id:'char16', name:'ロボ',      emoji:'🤖', unlockId:'log100',
    description:'コツコツ記録するロボット',
    colorMap:{}, customGrids:{ slim:C16S, chubby:C16C, fat:C16F } },
  { id:'char17', name:'まほう',    emoji:'✨', unlockId:'streak60',
    description:'ふしぎな力を持つまほうつかい',
    colorMap:{}, customGrids:{ slim:C17S, chubby:C17C, fat:C17F } },
  { id:'char18', name:'かいぞく',  emoji:'🏴‍☠️', unlockId:'pet100',
    description:'海を渡るワイルドなかいぞく',
    colorMap:{}, customGrids:{ slim:C18S, chubby:C18C, fat:C18F } },
  { id:'char19', name:'てんし',    emoji:'😇', unlockId:'mission50',
    description:'純粋でやさしいてんし',
    colorMap:{}, customGrids:{ slim:C19S, chubby:C19C, fat:C19F } },
  { id:'char20', name:'おうさま',  emoji:'👑', unlockId:'streak100',
    description:'全てを達成した伝説のおうさま',
    colorMap:{}, customGrids:{ slim:C20S, chubby:C20C, fat:C20F } },
];

// ── Helpers ───────────────────────────────────────────────────────────────────

function applyColorMap(grid: Grid, colorMap: Record<string, string>): Grid {
  if (!Object.keys(colorMap).length) return grid;
  return grid.map(row => row.map(cell => (cell && colorMap[cell]) ? colorMap[cell] : cell));
}

export function getCharPixels(characterId: string, stage: number): Grid {
  const base = BASE_GRIDS[Math.min(stage, 5)] ?? EGG;
  if (stage === 0 || stage >= 4) return base;          // EGG / ZOMBIE / DEAD は共通
  const char = CHARACTERS.find(c => c.id === characterId);
  if (!char) return base;
  if (char.customGrids) {
    if (stage === 1) return char.customGrids.slim;
    if (stage === 2) return char.customGrids.chubby;
    if (stage === 3) return char.customGrids.fat;
  }
  if (!Object.keys(char.colorMap).length) return base;
  return applyColorMap(base, char.colorMap);
}
